name: deploy

# 在main分支发生push事件时触发。
on:
  push:
    branches:
      - main

env: # 设置环境变量
  TZ: Asia/Shanghai # 时区（设置时区可使页面中的`最近更新时间`使用时区时间）

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest # 运行在虚拟机环境ubuntu-latest

    steps:
      # 检出
      - name: Checkout
        uses: actions/checkout@v3
        with:
          persist-credentials: false

        # 安装 node
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: "16.x"
          registry-url: "https://registry.npmjs.org"
          # cache: "yarn"

        # 构建
      - name: Build
        run: |
          yarn install
          yarn build

        # 同步到又拍云
      # - name: Deploy upyun
      #   run: |
      #     wget -O upx.tar.gz http://collection.b0.upaiyun.com/softwares/upx/upx_0.3.6_linux_x86_64.tar.gz
      #     tar -zxf upx.tar.gz
      #     chmod +x upx
      #     ./upx login ${{ secrets.UP_BUCKET }} ${{ secrets.UP_OPERATOR }} ${{ secrets.UP_OPERATOR_PASSWORD }}
      #     ./upx sync dist/ / --delete
      #     ./upx logout

      # 发布到 gh-page 分支
      - name: Deploy github
        uses: JamesIves/github-pages-deploy-action@v4.3.3
        with:
          token: ${{ secrets.ACCESS_TOKEN }}
          branch: gh-pages # 部署后提交到那个分支
          folder: ./dist # 这里填打包好的目录名称



